# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_processer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 821)
        MainWindow.setMaximumSize(QtCore.QSize(1067, 821))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 13, 1021, 701))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(331, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.original_image = QtWidgets.QLabel(self.layoutWidget)
        self.original_image.setMaximumSize(QtCore.QSize(600, 600))
        self.original_image.setText("")
        self.original_image.setScaledContents(True)
        self.original_image.setObjectName("original_image")
        self.verticalLayout.addWidget(self.original_image)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(281, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.processed_image = QtWidgets.QLabel(self.layoutWidget)
        self.processed_image.setMaximumSize(QtCore.QSize(600, 600))
        self.processed_image.setText("")
        self.processed_image.setScaledContents(True)
        self.processed_image.setObjectName("processed_image")
        self.verticalLayout_3.addWidget(self.processed_image)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.setStretch(0, 5)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionHyprid_Image = QtWidgets.QAction(MainWindow)
        self.actionHyprid_Image.setObjectName("actionHyprid_Image")
        self.actionRGB_Histogram = QtWidgets.QAction(MainWindow)
        self.actionRGB_Histogram.setObjectName("actionRGB_Histogram")
        self.actionImage_Equalization = QtWidgets.QAction(MainWindow)
        self.actionImage_Equalization.setObjectName("actionImage_Equalization")
        self.actionImage_Normalization = QtWidgets.QAction(MainWindow)
        self.actionImage_Normalization.setObjectName("actionImage_Normalization")
        self.actionGlobal_Threshold = QtWidgets.QAction(MainWindow)
        self.actionGlobal_Threshold.setObjectName("actionGlobal_Threshold")
        self.actionLocal_Threshold = QtWidgets.QAction(MainWindow)
        self.actionLocal_Threshold.setObjectName("actionLocal_Threshold")
        self.actionImage_Recognition = QtWidgets.QAction(MainWindow)
        self.actionImage_Recognition.setObjectName("actionImage_Recognition")
        self.actionImage_Detection = QtWidgets.QAction(MainWindow)
        self.actionImage_Detection.setObjectName("actionImage_Detection")
        self.menuFile.addAction(self.actionImage_Recognition)
        self.menuFile.addAction(self.actionImage_Detection)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Processer"))
        self.label.setText(_translate("MainWindow", "  Original Image"))
        self.label_4.setText(_translate("MainWindow", "  Processed Image "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Filters"))
        self.menuFile.setTitle(_translate("MainWindow", "Options"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Image Detection"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionHyprid_Image.setText(_translate("MainWindow", "Hyprid Image"))
        self.actionRGB_Histogram.setText(_translate("MainWindow", "RGB Histogram"))
        self.actionImage_Equalization.setText(_translate("MainWindow", "Image Equalization"))
        self.actionImage_Normalization.setText(_translate("MainWindow", "Image Normalization"))
        self.actionGlobal_Threshold.setText(_translate("MainWindow", "Global Threshold"))
        self.actionLocal_Threshold.setText(_translate("MainWindow", "Local Threshold"))
        self.actionImage_Recognition.setText(_translate("MainWindow", "Face Recognition"))
        self.actionImage_Detection.setText(_translate("MainWindow", "Face Detection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

